from pathlib import Path

import numpy as np
import pandas as pd


# ============================================================
# NIFTY 50 MODEL 10 — PROSPECTIVE HOLDOUT EVALUATOR
# ============================================================
#
# IMPORTANT:
# - Does NOT retrain Model 10.
# - Does NOT modify predictions.
# - Does NOT optimize thresholds.
# - Uses only predictions already generated by the
#   prospective holdout engine.
# - Actual T+1 outcome is joined only after it becomes
#   available in the feature dataset.
#
# ============================================================


BASE_DIR = Path(__file__).resolve().parents[1]

PREDICTIONS_FILE = (
    BASE_DIR
    / "data"
    / "nifty50_model10_large_move"
    / "model10_holdout_predictions.csv"
)

FEATURE_FILE = (
    BASE_DIR
    / "data"
    / "nifty50_features"
    / "nifty50_t1_features.csv"
)

HOLDOUT_LOCK_FILE = (
    BASE_DIR
    / "data"
    / "nifty50_model10_large_move"
    / "model10_holdout_lock.csv"
)

OUTPUT_DIR = (
    BASE_DIR
    / "data"
    / "nifty50_model10_large_move"
)

EVALUATED_FILE = (
    OUTPUT_DIR
    / "model10_holdout_evaluated.csv"
)

SUMMARY_FILE = (
    OUTPUT_DIR
    / "model10_holdout_summary.csv"
)

RANKING_FILE = (
    OUTPUT_DIR
    / "model10_holdout_ranking.csv"
)


# ============================================================
# FROZEN HOLDOUT DEFINITION
# ============================================================

HOLDOUT_START_DATE = pd.Timestamp("2026-09-11")

TOP_FRACTION = 0.20
BOTTOM_FRACTION = 0.20

BOOTSTRAP_ITERATIONS = 10000
PERMUTATION_ITERATIONS = 10000

RANDOM_STATE = 42


def calculate_difference(top_values, bottom_values):
    return (
        top_values.mean()
        - bottom_values.mean()
    )


def bootstrap_difference(
    top_values,
    bottom_values,
    iterations=BOOTSTRAP_ITERATIONS,
    random_state=RANDOM_STATE,
):

    rng = np.random.default_rng(
        random_state
    )

    top_values = np.asarray(
        top_values,
        dtype=float
    )

    bottom_values = np.asarray(
        bottom_values,
        dtype=float
    )

    differences = np.empty(
        iterations,
        dtype=float
    )

    for i in range(iterations):

        top_sample = rng.choice(
            top_values,
            size=len(top_values),
            replace=True,
        )

        bottom_sample = rng.choice(
            bottom_values,
            size=len(bottom_values),
            replace=True,
        )

        differences[i] = (
            top_sample.mean()
            - bottom_sample.mean()
        )

    lower = np.percentile(
        differences,
        2.5
    )

    upper = np.percentile(
        differences,
        97.5
    )

    probability_positive = np.mean(
        differences > 0
    )

    return (
        lower,
        upper,
        probability_positive
    )


def permutation_test(
    top_values,
    bottom_values,
    iterations=PERMUTATION_ITERATIONS,
    random_state=RANDOM_STATE,
):

    rng = np.random.default_rng(
        random_state
    )

    top_values = np.asarray(
        top_values,
        dtype=float
    )

    bottom_values = np.asarray(
        bottom_values,
        dtype=float
    )

    observed = (
        top_values.mean()
        - bottom_values.mean()
    )

    combined = np.concatenate(
        [
            top_values,
            bottom_values
        ]
    )

    top_size = len(top_values)

    exceed_count = 0

    for _ in range(iterations):

        shuffled = rng.permutation(
            combined
        )

        shuffled_top = shuffled[
            :top_size
        ]

        shuffled_bottom = shuffled[
            top_size:
        ]

        difference = (
            shuffled_top.mean()
            - shuffled_bottom.mean()
        )

        if abs(difference) >= abs(observed):

            exceed_count += 1

    # +1 correction prevents reporting zero
    # p-values.
    p_value = (
        exceed_count + 1
    ) / (
        iterations + 1
    )

    return p_value


def main():

    print("=" * 70)
    print(
        "NIFTY 50 MODEL 10 — PROSPECTIVE HOLDOUT EVALUATOR"
    )
    print("=" * 70)

    # ========================================================
    # 1. FILE CHECKS
    # ========================================================

    if not PREDICTIONS_FILE.exists():

        raise FileNotFoundError(
            f"Missing holdout prediction file:\n"
            f"{PREDICTIONS_FILE}"
        )

    if not FEATURE_FILE.exists():

        raise FileNotFoundError(
            f"Missing feature file:\n"
            f"{FEATURE_FILE}"
        )

    if not HOLDOUT_LOCK_FILE.exists():

        raise FileNotFoundError(
            f"Missing holdout lock file:\n"
            f"{HOLDOUT_LOCK_FILE}"
        )

    # ========================================================
    # 2. VERIFY HOLDOUT LOCK
    # ========================================================

    lock = pd.read_csv(
        HOLDOUT_LOCK_FILE
    )

    if len(lock) != 1:

        raise ValueError(
            "Holdout lock must contain exactly one row."
        )

    locked_start = pd.Timestamp(
        lock.loc[0, "holdout_start_date"]
    )

    if locked_start != HOLDOUT_START_DATE:

        raise ValueError(
            "Holdout start date does not match "
            "the frozen holdout lock."
        )

    # ========================================================
    # 3. LOAD PROSPECTIVE PREDICTIONS
    # ========================================================

    predictions = pd.read_csv(
        PREDICTIONS_FILE
    )

    if len(predictions) == 0:

        print()
        print(
            "No prospective holdout predictions "
            "are currently available."
        )

        print()
        print(
            "STATUS: WAITING"
        )

        print("=" * 70)

        return

    required_prediction_columns = {
        "date",
        "probability_large_move",
        "prediction",
    }

    missing_prediction_columns = (
        required_prediction_columns
        - set(predictions.columns)
    )

    if missing_prediction_columns:

        raise ValueError(
            "Missing prediction columns: "
            f"{sorted(missing_prediction_columns)}"
        )

    predictions["date"] = pd.to_datetime(
        predictions["date"]
    )

    predictions = (
        predictions
        .sort_values("date")
        .drop_duplicates(
            "date",
            keep="first"
        )
        .reset_index(drop=True)
    )

    # ========================================================
    # 4. SAFETY CHECKS ON PREDICTIONS
    # ========================================================

    if (
        predictions["date"]
        < HOLDOUT_START_DATE
    ).any():

        raise AssertionError(
            "Pre-holdout prediction detected."
        )

    if (
        predictions["probability_large_move"]
        .isna()
        .any()
    ):

        raise AssertionError(
            "Missing prediction probability detected."
        )

    if (
        (
            predictions[
                "probability_large_move"
            ] < 0
        )
        |
        (
            predictions[
                "probability_large_move"
            ] > 1
        )
    ).any():

        raise AssertionError(
            "Prediction probability outside [0,1]."
        )

    # ========================================================
    # 5. LOAD ACTUAL T+1 OUTCOMES
    # ========================================================

    features = pd.read_csv(
        FEATURE_FILE
    )

    features["date"] = pd.to_datetime(
        features["date"]
    )

    required_feature_columns = {
        "date",
        "nifty_t1_return",
    }

    missing_feature_columns = (
        required_feature_columns
        - set(features.columns)
    )

    if missing_feature_columns:

        raise ValueError(
            "Missing actual-outcome columns: "
            f"{sorted(missing_feature_columns)}"
        )

    features = (
        features
        .sort_values("date")
        .drop_duplicates(
            "date",
            keep="last"
        )
        .reset_index(drop=True)
    )

    actuals = features[
        [
            "date",
            "nifty_t1_return",
        ]
    ].copy()

    # ========================================================
    # 6. JOIN PREDICTIONS TO ACTUAL OUTCOMES
    # ========================================================

    evaluated = predictions.merge(
        actuals,
        on="date",
        how="left",
        validate="one_to_one",
    )

    # ========================================================
    # 7. ONLY EVALUATE OUTCOMES THAT HAVE ARRIVED
    # ========================================================

    evaluated["actual_large_move"] = np.where(
        evaluated["nifty_t1_return"].notna(),
        (
            evaluated[
                "nifty_t1_return"
            ].abs()
            >= 0.01
        ).astype(int),
        np.nan,
    )

    completed = evaluated[
        evaluated["nifty_t1_return"].notna()
    ].copy()

    completed = (
        completed
        .sort_values("date")
        .reset_index(drop=True)
    )

    # ========================================================
    # 8. SAVE EVALUATED RECORDS
    # ========================================================

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    evaluated.to_csv(
        EVALUATED_FILE,
        index=False
    )

    print()
    print("HOLDOUT DATA")
    print("-" * 70)

    print(
        f"Predictions available : "
        f"{len(predictions)}"
    )

    print(
        f"Outcomes available    : "
        f"{len(completed)}"
    )

    print(
        f"Outcomes pending      : "
        f"{len(predictions) - len(completed)}"
    )

    if len(completed) == 0:

        print()
        print(
            "No T+1 outcomes are currently available "
            "for evaluation."
        )

        print()
        print(
            f"Evaluated file: {EVALUATED_FILE}"
        )

        print()
        print(
            "STATUS: WAITING"
        )

        print("=" * 70)

        return

    # ========================================================
    # 9. FIXED GLOBAL TOP/BOTTOM 20% RANKING
    # ========================================================
    #
    # This ranking is based ONLY on Model 10 probabilities.
    #
    # No threshold optimization.
    # No outcome-based ranking.
    # ========================================================

    completed = (
        completed
        .sort_values(
            "probability_large_move",
            ascending=False
        )
        .reset_index(drop=True)
    )

    n = len(completed)

    top_count = int(
        np.floor(
            n * TOP_FRACTION
        )
    )

    bottom_count = int(
        np.floor(
            n * BOTTOM_FRACTION
        )
    )

    if top_count < 1 or bottom_count < 1:

        print()
        print(
            "Insufficient completed holdout observations "
            "to form TOP/BOTTOM 20% groups."
        )

        print(
            f"Completed observations: {n}"
        )

        print()
        print(
            "STATUS: WAITING"
        )

        print("=" * 70)

        return

    completed["ranking_group"] = "MIDDLE_60"

    completed.loc[
        : top_count - 1,
        "ranking_group"
    ] = "TOP_20"

    completed.loc[
        n - bottom_count :,
        "ranking_group"
    ] = "BOTTOM_20"

    # ========================================================
    # 10. GROUP SUMMARY
    # ========================================================

    group_rows = []

    overall_rate = (
        completed[
            "actual_large_move"
        ].mean()
    )

    for group_name in [
        "TOP_20",
        "MIDDLE_60",
        "BOTTOM_20",
    ]:

        group = completed[
            completed[
                "ranking_group"
            ] == group_name
        ]

        event_rate = (
            group[
                "actual_large_move"
            ].mean()
        )

        lift = (
            event_rate / overall_rate
            if overall_rate > 0
            else np.nan
        )

        group_rows.append(
            {
                "group": group_name,
                "observations": len(group),
                "large_move_rate": event_rate,
                "average_probability": (
                    group[
                        "probability_large_move"
                    ].mean()
                ),
                "lift_vs_overall": lift,
            }
        )

    ranking_summary = pd.DataFrame(
        group_rows
    )

    ranking_summary.to_csv(
        RANKING_FILE,
        index=False
    )

    # ========================================================
    # 11. TOP-BOTTOM STATISTICAL TEST
    # ========================================================

    top_values = completed[
        completed["ranking_group"] == "TOP_20"
    ][
        "actual_large_move"
    ].to_numpy()

    bottom_values = completed[
        completed["ranking_group"] == "BOTTOM_20"
    ][
        "actual_large_move"
    ].to_numpy()

    observed_difference = (
        top_values.mean()
        - bottom_values.mean()
    )

    ci_lower, ci_upper, probability_positive = (
        bootstrap_difference(
            top_values,
            bottom_values,
        )
    )

    permutation_p = permutation_test(
        top_values,
        bottom_values,
    )

    # ========================================================
    # 12. SUMMARY
    # ========================================================

    top_rate = top_values.mean()

    bottom_rate = bottom_values.mean()

    summary = pd.DataFrame(
        [
            {
                "holdout_start_date": (
                    HOLDOUT_START_DATE.date()
                ),
                "completed_observations": len(
                    completed
                ),
                "overall_large_move_rate": (
                    overall_rate
                ),
                "top_20_observations": (
                    len(top_values)
                ),
                "top_20_large_move_rate": (
                    top_rate
                ),
                "bottom_20_observations": (
                    len(bottom_values)
                ),
                "bottom_20_large_move_rate": (
                    bottom_rate
                ),
                "top_minus_bottom_difference": (
                    observed_difference
                ),
                "top_20_lift": (
                    top_rate / overall_rate
                    if overall_rate > 0
                    else np.nan
                ),
                "bottom_20_lift": (
                    bottom_rate / overall_rate
                    if overall_rate > 0
                    else np.nan
                ),
                "bootstrap_iterations": (
                    BOOTSTRAP_ITERATIONS
                ),
                "bootstrap_ci_lower": (
                    ci_lower
                ),
                "bootstrap_ci_upper": (
                    ci_upper
                ),
                "bootstrap_probability_difference_gt_zero": (
                    probability_positive
                ),
                "permutation_iterations": (
                    PERMUTATION_ITERATIONS
                ),
                "permutation_p_value": (
                    permutation_p
                ),
                "statistically_significant_5pct": (
                    permutation_p < 0.05
                ),
                "statistically_significant_1pct": (
                    permutation_p < 0.01
                ),
            }
        ]
    )

    summary.to_csv(
        SUMMARY_FILE,
        index=False
    )

    # ========================================================
    # 13. REPORT
    # ========================================================

    print()
    print("HOLDOUT EVALUATION")
    print("-" * 70)

    print(
        f"Completed observations : "
        f"{len(completed)}"
    )

    print(
        f"Coverage               : "
        f"{completed['date'].min().date()} -> "
        f"{completed['date'].max().date()}"
    )

    print(
        f"Overall large-move rate: "
        f"{overall_rate:.6f}"
    )

    print()
    print("FIXED RANKING")
    print("-" * 70)

    print(
        f"TOP 20% observations   : "
        f"{len(top_values)}"
    )

    print(
        f"TOP 20% event rate     : "
        f"{top_rate:.6f}"
    )

    print(
        f"TOP 20% lift           : "
        f"{top_rate / overall_rate:.6f}"
    )

    print()

    print(
        f"BOTTOM 20% observations: "
        f"{len(bottom_values)}"
    )

    print(
        f"BOTTOM 20% event rate  : "
        f"{bottom_rate:.6f}"
    )

    print(
        f"BOTTOM 20% lift        : "
        f"{bottom_rate / overall_rate:.6f}"
    )

    print()

    print(
        f"TOP-BOTTOM difference  : "
        f"{observed_difference:.6f}"
    )

    print()
    print("STATISTICAL TEST")
    print("-" * 70)

    print(
        f"Bootstrap iterations   : "
        f"{BOOTSTRAP_ITERATIONS}"
    )

    print(
        f"95% CI lower           : "
        f"{ci_lower:.6f}"
    )

    print(
        f"95% CI upper           : "
        f"{ci_upper:.6f}"
    )

    print(
        f"P(bootstrap diff > 0) : "
        f"{probability_positive:.6f}"
    )

    print()

    print(
        f"Permutation iterations : "
        f"{PERMUTATION_ITERATIONS}"
    )

    print(
        f"Permutation p-value    : "
        f"{permutation_p:.6f}"
    )

    print(
        f"Significant at 5%      : "
        f"{permutation_p < 0.05}"
    )

    print(
        f"Significant at 1%      : "
        f"{permutation_p < 0.01}"
    )

    print()
    print("OUTPUT FILES")
    print("-" * 70)

    print(
        f"Evaluated data         : "
        f"{EVALUATED_FILE}"
    )

    print(
        f"Summary                : "
        f"{SUMMARY_FILE}"
    )

    print(
        f"Ranking                : "
        f"{RANKING_FILE}"
    )

    print()
    print("IMPORTANT")
    print("-" * 70)
    print(
        "Predictions were NOT changed."
    )

    print(
        "Model was NOT retrained."
    )

    print(
        "Features were NOT changed."
    )

    print(
        "Threshold was NOT optimized."
    )

    print(
        "Holdout start date was NOT changed."
    )

    print()
    print("STATUS: PASS")
    print("=" * 70)


if __name__ == "__main__":
    main()