"""add_portfolio_price_columns

Revision ID: ac834f1c58ca
Revises: 7fdee56c6dcd
Create Date: 2026-08-02 15:11:14.594581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac834f1c58ca'
down_revision: Union[str, Sequence[str], None] = '7fdee56c6dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('current_price', sa.Float(), nullable=True))
    op.add_column('portfolio', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'last_updated')
    op.drop_column('portfolio', 'current_price')
    # ### end Alembic commands ###
