"""add_realized_profit

Revision ID: d0995f7e8d4c
Revises: 520ef55ffe41
Create Date: 2026-08-02 16:20:14.571315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0995f7e8d4c'
down_revision: Union[str, Sequence[str], None] = '520ef55ffe41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('realized_profit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'realized_profit')
    # ### end Alembic commands ###
